<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1-Create Note</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3d702f42-b0c5-4df8-a243-3072b022ba59</testSuiteGuid>
   <testCaseLink>
      <guid>d189c8a1-c18e-417f-a9e8-0f5bf214978f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1_Create Note/1.1_Successfully Create Simple Text Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a91b4d71-b5f5-44e3-9837-6ae7115e13a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f20d5ab6-4d73-41f1-a3fe-880825026531</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f356a7d3-d127-4b00-bae5-73ea89b8edc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1_Create Note/1.2_Successfully Create Simple Checklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99ba7071-0291-4440-b3db-0ce2d4ef6d2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9077d740-21f7-400e-be0a-6381fa9f2692</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
