<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS3-Set Reminder and Archive Text Note</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8ce7e4ee-a4e2-4220-997f-ac51c8d5d913</testSuiteGuid>
   <testCaseLink>
      <guid>b8a22aad-86fa-4773-9d02-0b9f2aa31252</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/3_Set Reminder/3.1_Successfully set reminder for text note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa7a02b9-74a5-4676-85e3-28f6b2ce374f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26d850b9-6c52-4723-942e-e440d8a8d940</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29fde87f-7c59-48bb-ae86-13e2003367dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6827687d-65e5-4914-a0df-1229a20dd244</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72bb15cf-52a2-444f-b79b-6ed5a5bc44ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ea4ebb1-648a-4af7-99f3-ae4597ae07c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/3_Set Reminder/3.2_Successfully set reminder for checklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fef97957-93de-4692-8360-1168c9ebea9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b77f720e-44d6-40ce-adbf-b15083179bd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b02fdce4-77a0-417c-a42e-17105add4bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0705108f-8f6f-4926-8699-9cf4e4efde82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5cd941c-945c-488c-a7d9-09a17370285a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/3_Set Reminder/3.3_Users archive the note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7effb3be-0405-4fa1-a184-6e9dcd8b2bcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abcf7a9-f422-4086-91cf-0d74e1803ad3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
