<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1, TS4 - Create Note and Edit_Revert Note</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b2964178-15c4-4c80-8af5-67efb1c2b82a</testSuiteGuid>
   <testCaseLink>
      <guid>a1bdb547-bb92-4c64-9771-8b6ff3ddbf96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1_Create Note/1.1_Successfully Create Simple Text Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a91b4d71-b5f5-44e3-9837-6ae7115e13a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f20d5ab6-4d73-41f1-a3fe-880825026531</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c5a6fa9-7337-4b1e-bc31-292d3ff18bd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1_Create Note/1.2_Successfully Create Simple Checklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99ba7071-0291-4440-b3db-0ce2d4ef6d2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9077d740-21f7-400e-be0a-6381fa9f2692</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e0d66c8-f7fb-4fa0-ac6e-60bc4a5f6349</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4_Edit the Note/4.1_Edit the text note and revert</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aae22820-4648-404d-8faf-8db337d0c76e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ddbfbf8-9260-4dd8-bab9-f8015b6f7334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b07b6faf-1e76-486f-a6b0-81b94c39c128</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>732916ea-677d-4103-afce-90406b90f20a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2adee266-d23d-4e07-84dc-f44e3042a41c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4_Edit the Note/4.2_Edit the checklist and revert</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4a3fc9d-4d9a-4aec-9bc1-cfc87384d6ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1122acb5-9602-4003-b05c-4951e169f38c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0df6c58e-f320-4669-8ea8-98670e5075e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d205744-174a-46ea-9a93-752fc52cf7b7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
